### PR TITLE
add Flux 0.11 compat

### PR DESCRIPTION
**Pull request by johnnychen94**

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
For Flux@0.11, it's best to bump the Julia version bounds as well and maybe allow failure on nightly for the time being

**Comment by johnnychen94** [comment]
> For Flux@0.11, it's best to bump the Julia version bounds as well

Would you mind elaborating this more? I don't get why we need to bump the Julia version here; `Flux@0.11` is compatible with `Julia 1.3` and Pkg resolves CUDA to `1.0.2`. It makes more sense to bump the Julia version in upstream `Flux` if this is actually incompatible.

**Comment by DhairyaLGandhi** [comment]
Flux is compatible yes, it's not a necessity, as you pointed out, but going forward it may be that we might have to bump the Julia version if there are fixes that we need from the CUDA side.

**Comment by johnnychen94** [comment]
Not following very closely, I probably haven't captured the big picture there about the CUDA and Flux integration, so I'll leave this to you if you think it's worth a compat bump to Julia version :P

If I get it correctly, Github Action seems not supporting `allow_failures` feature yet, so I just disabled the default `fail_fast` behavior.

**Comment by DhairyaLGandhi** [comment]
Super, thanks!

**Pull request merged**
